blank_issues_enabled: true
contact_links:
  - name: Koinos documentation
    url: https://docs.koinos.io/
    about: Check out the documentation to learn about features and usage
  - name: Koinos website
    url: https://koinos.io/
    about: Latest news and information can be found on the Koinos website
  - name: Koinos on Discord
    url: https://discord.com/invite/GErGNsu
    about: Join the conversation about Koinos on Discord
  - name: Koinos on Telegram
    url: https://t.me/joinchat/SXe6mLnb8Ssywlq9
    about: Join the conversation about Koinos on Telegram
  - name: Koinos on Twitter
    url: https://twitter.com/koinosnetwork
    about: Learn about the latest news about Koinos on Twitter
  - name: Koinos on YouTube
    url: https://www.youtube.com/channel/UCamXqlj7q14TllcrCM0ikkw
    about: Watch tutorials, interviews with the developers, and more on YouTube

